#! /bin/sh

sxhkd &
nitrogen --restore
picom

$HOME/.config/polybar/launch.sh

bspc monitor DP-1-4 -d VI VII VIII IX X
bspc monitor eDP-1 -d   I II III IV V

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname LG3D &
bspc rule -a android-studio state=floating border=off follow=on
